
name: Build and Tests

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.2

      - name: Install dependent
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
